alias fslex="dotnet ../fsharp/fslex.dll"
alias fsyacc="dotnet ../fsharp/fsyacc.dll"
alias genpar="dotnet ../fsharp/fsyacc.dll --module FunPar ./FunPar.fsy"
alias genlex="dotnet ../fsharp/fslex.dll --unicode ./FunLex.fsl"
alias runhf="dotnet fsi -r ../fsharp/FsLexYacc.Runtime.dll Util.fs Absyn.fs FunPar.fs FunLex.fs Parse.fs HigherFun.fs ParseAndRunHigher.fs"
alias runti="dotnet fsi -r ../fsharp/FsLexYacc.Runtime.dll Util.fs Absyn.fs FunPar.fs FunLex.fs Parse.fs TypeInference.fs ParseAndType.fs"
alias clean="rm FunLex.fs FunLex.fsi FunPar.fs FunPar.fsi"